//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaturdaysChild.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberMessage
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Alert { get; set; }
        public string MemberName { get; set; }
        public string Message { get; set; }
        public string From { get; set; }
        public bool IsEmployee { get; set; }
        public bool IsRead { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
    }
}
