//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaturdaysChild.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteAccess
    {
        public int Id { get; set; }
        public string Psuedonym { get; set; }
        public System.DateTime Login { get; set; }
        public Nullable<System.DateTime> Logout { get; set; }
        public byte[] IPAddress { get; set; }
        public string MACAddress { get; set; }
    }
}
