//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaturdaysChild.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportTicket
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public int ClientId { get; set; }
        public int ContractId { get; set; }
        public string ContactName { get; set; }
        public string Contact { get; set; }
        public System.DateTime TicketStart { get; set; }
        public Nullable<System.DateTime> TicketEnd { get; set; }
        public string Notes { get; set; }
        public Nullable<int> BugId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual BugReport BugReport { get; set; }
    }
}
