//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaturdaysChild.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItem
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int ContractId { get; set; }
        public Nullable<int> TimesheetId { get; set; }
        public int LaborCategoryId { get; set; }
        public int LaborTypeId { get; set; }
        public string WorkSite { get; set; }
        public bool Billed { get; set; }
        public int Hours { get; set; }
        public string Description { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual LaborCategory LaborCategory { get; set; }
        public virtual LaborType LaborType { get; set; }
        public virtual Timesheet Timesheet { get; set; }
    }
}
